In [186]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import opendatasets as od

In [187]:
bugs_df= pd.read_csv("Firefoxbuglist.csv")
# eclispsebugs= pd.read_csv("Eclipsebuglist.csv")
# calendarbugs= pd.read_csv("Calendarbuglist.csv")

In [188]:
# bugs_df = pd.concat([firefoxbugs, eclispsebugs,calendarbugs])

In [189]:
# print(len(firefoxbugs), len(eclispsebugs), len(calendarbugs))

len(bugs_df)

10000

In [190]:
file_name = 'BugCombinedData.xlsx'
  
# saving the excel
#bugs_df.to_excel(file_name)
print('DataFrame is written to Excel File successfully.')

DataFrame is written to Excel File successfully.


In [191]:
bugs_df.head(5)

Bug ID  Product            Component     Assignee    Status Resolution  \
0   276934  Firefox  Keyboard Navigation     aaronlev  RESOLVED  DUPLICATE   
1  1589425  Firefox     Messaging System      abenson  RESOLVED    WONTFIX   
2  1712221  Firefox         New Tab Page  achurchwell  RESOLVED    WONTFIX   
3  1720578  Firefox            Top Sites  achurchwell  RESOLVED  DUPLICATE   
4  1750788  Firefox         New Tab Page  achurchwell  RESOLVED    INVALID   

                                             Summary Change Request Priority  \
0  After closing tab, Space doesn't scroll down o...            ---       P1   
1             Promoting Picture in Picture using CFR            ---       P1   
2            Update "personalize" drawer drop shadow            ---       P1   
3  Sponsored Topsites should retrieve their icons...            ---       P1   
4        Add ability for New Tab Page to set a theme            ---       P1   

  Severity  
0   normal  
1   normal  
2       --  
3       --  
4       --

In [192]:
bugs_df.describe()

Bug ID
count  1.000000e+04
mean   1.255332e+06
std    4.596195e+05
min    1.095400e+04
25%    1.096952e+06
50%    1.425026e+06
75%    1.585128e+06
max    1.761378e+06

In [193]:
bugs_df.describe(include='O')

Product Component Assignee    Status  Resolution  \
count     10000     10000    10000     10000       10000   
unique        1        50      327         1           8   
top     Firefox   General   nobody  RESOLVED  INCOMPLETE   
freq      10000      1367     8045     10000        2999   

                                                  Summary Change Request  \
count                                               10000          10000   
unique                                               9803              1   
top     Intermittent browser/base/content/test/general...            ---   
freq                                                    5          10000   

       Priority Severity  
count     10000     9912  
unique        6       11  
top          P5   normal  
freq       3925     7404

In [194]:
bugs_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Bug ID          10000 non-null  int64 
 1   Product         10000 non-null  object
 2   Component       10000 non-null  object
 3   Assignee        10000 non-null  object
 4   Status          10000 non-null  object
 5   Resolution      10000 non-null  object
 6   Summary         10000 non-null  object
 7   Change Request  10000 non-null  object
 8   Priority        10000 non-null  object
 9   Severity        9912 non-null   object
dtypes: int64(1), object(9)
memory usage: 781.4+ KB


In [195]:
bugs_df=bugs_df.dropna().reset_index(drop=True)

In [196]:
len(bugs_df)

9912

In [197]:
bugs_df = bugs_df[bugs_df["Severity"].str.contains("--")==False].reset_index()

In [198]:
len(bugs_df)

9692

In [199]:
bugs_df.head(5)

index   Bug ID  Product            Component  Assignee    Status  \
0      0   276934  Firefox  Keyboard Navigation  aaronlev  RESOLVED   
1      1  1589425  Firefox     Messaging System   abenson  RESOLVED   
2      5  1060367  Firefox               Search       adw  RESOLVED   
3      6  1326826  Firefox               Search       adw  RESOLVED   
4      7  1328104  Firefox               Search       adw  RESOLVED   

   Resolution                                            Summary  \
0   DUPLICATE  After closing tab, Space doesn't scroll down o...   
1     WONTFIX             Promoting Picture in Picture using CFR   
2  WORKSFORME  [e10s] Search engine add-ons using POST do not...   
3   DUPLICATE  Popup with search suggestions hides on 'moused...   
4   DUPLICATE             Add Search Engine Button Does Not Work   

  Change Request Priority Severity  
0            ---       P1   normal  
1            ---       P1   normal  
2            ---       P1   normal  
3            ---       P1   normal  
4            ---       P1   normal

In [200]:
bugs_df.isnull().sum()

index             0
Bug ID            0
Product           0
Component         0
Assignee          0
Status            0
Resolution        0
Summary           0
Change Request    0
Priority          0
Severity          0
dtype: int64

In [201]:
bugs_df['Severity'].value_counts()

normal      7404
S4           937
major        335
critical     323
minor        258
S3           256
trivial       73
blocker       49
S2            46
S1            11
Name: Severity, dtype: int64

In [225]:
bugs_df.loc[bugs_df["Severity"] == "blocker", "Severity"] = 'Severe'
bugs_df.loc[bugs_df["Severity"] == "critical", "Severity"] = 'Severe'
bugs_df.loc[bugs_df["Severity"] == "major", "Severity"] = 'Severe'
bugs_df.loc[bugs_df["Severity"] == "S1", "Severity"] = 'Severe'
bugs_df.loc[bugs_df["Severity"] == "S2", "Severity"] = 'Severe'
bugs_df.loc[bugs_df["Severity"] == "S3", "Severity"] = 'Severe'
bugs_df.loc[bugs_df["Severity"] == "normal", "Severity"] = 'NonSevere'
bugs_df.loc[bugs_df["Severity"] == "minor", "Severity"] = 'NonSevere'
bugs_df.loc[bugs_df["Severity"] == "trivial", "Severity"] = 'NonSevere'
bugs_df.loc[bugs_df["Severity"] == "S4", "Severity"] = 'NonSevere'

In [226]:
bugs_df.Severity.unique()

array(['NonSevere', 'Severe'], dtype=object)

In [227]:
len(bugs_df)

9692

In [229]:
bugs_df.Summary.str.contains("Browser").sum()


117

# Correlation Attributes

In [230]:
bugs_df.corr()

#nominal attributes with class label
#Correlation Attributes
#Dictionary-- check in litreture
#dictionary for bug severity 
#Unique Words
#LR SVM

index    Bug ID
index   1.000000  0.061858
Bug ID  0.061858  1.000000

# Cleaning bug summary column

In [231]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to /Users/abyte/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [232]:
corpus = []
for i in range(0,9692):
    review = re.sub('[^a-zA-Z]', ' ', str(bugs_df['Summary'][i]))
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    all_stopwords = stopwords.words('english')
    all_stopwords.remove('not')
    review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
    review = ' '.join(review)
    corpus.append(review)

In [233]:
print(corpus)

['close tab space scroll one page', 'promot pictur pictur use cfr', 'e search engin add on use post not work e', 'popup search suggest hide mousedown button', 'add search engin button not work', 'one hover mouseov color darker match spec', 'icon page action popup explicitli set fill color', 'coupl awesom bar composit matchbucket pref user address bar state unifi vs bar', 'move unifiedcomplet js browser compon urlbar', 'implement select highlight', 'space around ident box separ divid asymmetr', 'nudg let extens set urlbar valu least clear', 'use fade gradient tip text', 'make propos v let experi extens creat result type custom view plu prototyp', 'forc muxer ignor built tip extens tip present', 'nvda screen reader read intervent card get help button mouseov', 'add analyt click send tab notif ui', 'creat dashboard valid data redash', 'crash content process due assert antitrackingcommon cpp', 'content block dispatch state cooki block tracker respons come cach', 'user unabl login pinterest

In [234]:
def convert(corpus):
    return ([i for item in corpus for i in item.split()])
     
print( convert(corpus))
splittedWords = convert(corpus)


['close', 'tab', 'space', 'scroll', 'one', 'page', 'promot', 'pictur', 'pictur', 'use', 'cfr', 'e', 'search', 'engin', 'add', 'on', 'use', 'post', 'not', 'work', 'e', 'popup', 'search', 'suggest', 'hide', 'mousedown', 'button', 'add', 'search', 'engin', 'button', 'not', 'work', 'one', 'hover', 'mouseov', 'color', 'darker', 'match', 'spec', 'icon', 'page', 'action', 'popup', 'explicitli', 'set', 'fill', 'color', 'coupl', 'awesom', 'bar', 'composit', 'matchbucket', 'pref', 'user', 'address', 'bar', 'state', 'unifi', 'vs', 'bar', 'move', 'unifiedcomplet', 'js', 'browser', 'compon', 'urlbar', 'implement', 'select', 'highlight', 'space', 'around', 'ident', 'box', 'separ', 'divid', 'asymmetr', 'nudg', 'let', 'extens', 'set', 'urlbar', 'valu', 'least', 'clear', 'use', 'fade', 'gradient', 'tip', 'text', 'make', 'propos', 'v', 'let', 'experi', 'extens', 'creat', 'result', 'type', 'custom', 'view', 'plu', 'prototyp', 'forc', 'muxer', 'ignor', 'built', 'tip', 'extens', 'tip', 'present', 'nvda', '

In [240]:
import collections
def getwordcounts(splittedWords):
    occurrences = collections.Counter(splittedWords)
    print(occurrences)
    return occurrences

splitted_words=getwordcounts(splittedWords)

Counter({'browser': 7851, 'test': 5277, 'js': 3789, 'intermitt': 3328, 'compon': 1909, 'content': 1722, 'not': 1435, 'time': 1401, 'tab': 1364, 'base': 1165, 'search': 983, 'window': 830, 'firefox': 724, 'bookmark': 640, 'except': 631, 'applic': 605, 'use': 599, 'open': 597, 'bar': 592, 'page': 562, 'error': 548, 'urlbar': 542, 'prefer': 527, 'uncaught': 497, 'timeout': 477, 'button': 462, 'url': 462, 'new': 426, 'unexpect': 423, 'expect': 419, 'sync': 416, 'pdf': 394, 'menu': 391, 'crash': 371, 'chrome': 371, 'gener': 354, 'x': 352, 'fail': 349, 'got': 343, 'code': 341, 'add': 331, 'tv': 323, 'file': 318, 'sessionstor': 310, 'chang': 306, 'place': 293, 'e': 281, 'show': 275, 'possibl': 273, 'work': 270, 'display': 270, 'perform': 265, 'click': 264, 'last': 263, 'close': 262, 'updat': 262, 'n': 262, 'second': 256, 'user': 255, 'split': 252, 'select': 251, 'exceed': 251, 'toolbar': 250, 'engin': 249, 'threshold': 247, 'rewritten': 247, 'bug': 241, 'mochitest': 237, 'default': 235, 'load

In [243]:
type(splitted_words)

collections.Counter

In [244]:
splitted_words.keys()

dict_keys(['close', 'tab', 'space', 'scroll', 'one', 'page', 'promot', 'pictur', 'use', 'cfr', 'e', 'search', 'engin', 'add', 'on', 'post', 'not', 'work', 'popup', 'suggest', 'hide', 'mousedown', 'button', 'hover', 'mouseov', 'color', 'darker', 'match', 'spec', 'icon', 'action', 'explicitli', 'set', 'fill', 'coupl', 'awesom', 'bar', 'composit', 'matchbucket', 'pref', 'user', 'address', 'state', 'unifi', 'vs', 'move', 'unifiedcomplet', 'js', 'browser', 'compon', 'urlbar', 'implement', 'select', 'highlight', 'around', 'ident', 'box', 'separ', 'divid', 'asymmetr', 'nudg', 'let', 'extens', 'valu', 'least', 'clear', 'fade', 'gradient', 'tip', 'text', 'make', 'propos', 'v', 'experi', 'creat', 'result', 'type', 'custom', 'view', 'plu', 'prototyp', 'forc', 'muxer', 'ignor', 'built', 'present', 'nvda', 'screen', 'reader', 'read', 'intervent', 'card', 'get', 'help', 'analyt', 'click', 'send', 'notif', 'ui', 'dashboard', 'valid', 'data', 'redash', 'crash', 'content', 'process', 'due', 'assert', '

In [236]:
bugs_df[
bugs_df["Summary"].str.lower().str.contains("browser")
]["Severity"].value_counts()

NonSevere    3347
Severe        127
Name: Severity, dtype: int64

In [237]:
len(bugs_df[
bugs_df["Severity"].str.lower().str.contains("browser")
])

0

In [246]:
splitted_words_dict = dict(splitted_words)

In [247]:
keys = splitted_word_dict.keys()

NameError: name 'splitted_word_dict' is not defined

In [ ]:
# Severe: 300
# NonSevere:500

In [183]:
from collections import Counter
  
# Function to get unique values
def unique(splittedWords):
    print(*Counter(splittedWords))
unique(splittedWords)
  

close tab space scroll one page promot pictur use cfr e search engin add on post not work popup suggest hide mousedown button hover mouseov color darker match spec icon action explicitli set fill coupl awesom bar composit matchbucket pref user address state unifi vs move unifiedcomplet js browser compon urlbar implement select highlight around ident box separ divid asymmetr nudg let extens valu least clear fade gradient tip text make propos v experi creat result type custom view plu prototyp forc muxer ignor built present nvda screen reader read intervent card get help analyt click send notif ui dashboard valid data redash crash content process due assert antitrackingcommon cpp block dispatch cooki tracker respons come cach unabl login pinterest via googl account standard url field top site editor pick imageri import bookmark show recommend cannot instal anymor messag target pin emerg plan welcom base attribut case return amo snippet local time trigger firefox releas mock enrol asrout 

rss stub synchron audio contextu winxp rtlpwaitforcriticalsect rtlentercriticalsect nseventlistenermanag discard shistorylisten uninterest reconcil wipe dodgi logic dupe constant comparison hmac verif consid reupload immedi mortar eslint hoc analysi deleg urlbarprovid amazon behind buildguidmap shut ship domain affin geoip databas weekli schedul interf gather earli permit unload ms bt care splash port ask overhead txul passphras restoreframechain xpcjscontextstack bottom submenu distinct tree hierarchi organis solari mozparam registri versu placehold tabmanag increment develop topolog extra stringbundl awkward bundl larg pain seamonkey polish die msaa effect st plt activeview wait capabl qi nsvoidarray indexof speed retriev spot alter finish balloon inject execut topcrash gtk trace malloc fxdbug tb kb flesh createdsmartbookmark addressbar ineffici repeatedli gapplicationspan patholog graph addabl piclen xa canva backup qm pxp ie transfer twinopen approv bss getnod buildbot safari accen

capturedtaskstack taskimpl ncreateasyncfunct asyncfunct ntask spawn ntaski documentnavig referenceerror correspond childprocess subtst wider terribl urlbarsearchsuggestionsnotif reauthent rv ptthread nfl blackground sanitizedialog titlenod escap raw nvidia blob switchtotabhavinguri aopenparam decodeuri rener visiturl rectangl oauth catagori categor feel tabfocu nsdefaulturifixup smush multiwindow can runinbatchmod placesuiut fuzzi medium syncengin syncnow clearemail contentdocu documentel contentcrashreport nsiurlclassifierdbservic beginupd higher em odd isdefault fragil remotenewtab pageload samsung nsresult pageact hi alia deepequ concept beforeunload smart logmanag cosmeticanim lin userstori clock misconfigur collis grace oop gbrowser visuallyselect bookmarkingui unstar grid closetab ggrid urlbardecod fexampl anonym runwatchdog void latvian aboutcerterror p pagemod onattach pluralsight cnn slice stuff garponlin idanl urlbartrimurl modaldialog chuclon formsubmitobserv singleton witho

 getstat addkeywordforthissearch fetchhighlight lib highlightsfe tmpmchzjk grcov ctype converttoj struct queryselector addbookmarkforfram quantumrend onchannelerrorfromlink urlbarplacehold wpt ws marionetteprotocol offlinedata reservedkey browsererrorreport autocompletepopup zone assertnotisweep vm typeinfer audiotabicon nssecurebrowseruiimpl onstatechang nsiwebprogress nsirequest gettabsforhomepag disclosur autoconfig insertnodeinwindow followonsearch followontelemetri sysaddon testdistribut reentrancyguard guardobjectnotifi gzipofflinechild proxyautoconfig beforehov checktelemetri defunct xwayland urlbarent primari frecenc sumofsquar scripttimeoutexcept filewatch pwa indicatordrop ua customizableuitestutil hidepanelmultiview privacyfilt topstori tmpeytioh testvalu sun ucasemap nsxpttype jsval xpconnect xpcwrappedn geckochildprocesshost ug testdelet testsessionstoredis nosuchwindowexcept preferencerolloutact setstart identitypopup jscov performasynclaunchinterna webassembl narrowest p

In [158]:
def frequencyofwordsineachcategory(x):


 return x

In [ ]:
# function that returns the number of each unique words in the corpus
# function to find the frequency of the word in each category Severe | Non Severe
#feature selection

dictionary = {
    
    Severe:["production","blocked","crashed","shutdown"]
    NonSevere:["scroll","menu","miss"]
}

In [135]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

In [136]:
transformed = tfidf.fit_transform(corpus)

In [137]:
df = pd.DataFrame(transformed[0].T.todense(),
    	index=tfidf.get_feature_names(), columns=["TF-IDF"])
df = df.sort_values('TF-IDF', ascending=False)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [138]:
df

TF-IDF
space                     0.511438
scroll                    0.468807
one                       0.439521
close                     0.387981
page                      0.324644
...                            ...
fullurl                   0.000000
fullscreenmod             0.000000
fullscreenandpointerlock  0.000000
fullscreen                0.000000
zxd                       0.000000

[5767 rows x 1 columns]

In [ ]:
## Find word frequency here from the corpus
# TF-IDF Vectorizer
#Frequency--- of words in 1 category Severe| NonSevere
#feature selction
#words appear in 1 category most than another


### Dictionary

In [108]:
import gensim
from gensim import corpora
from pprint import pprint
# from gensim.utils import simple_preprocess

In [100]:
processed_text = [[word for word in document.lower().split() if word not in all_stopwords]for document in corpus]

In [101]:
dictionary = corpora.Dictionary(processed_text)

In [102]:
print(dictionary.token2id)

{'close': 0, 'one': 1, 'page': 2, 'scroll': 3, 'space': 4, 'tab': 5, 'cfr': 6, 'pictur': 7, 'promot': 8, 'use': 9, 'add': 10, 'e': 11, 'engin': 12, 'not': 13, 'post': 14, 'search': 15, 'work': 16, 'button': 17, 'hide': 18, 'mousedown': 19, 'popup': 20, 'suggest': 21, 'color': 22, 'darker': 23, 'hover': 24, 'match': 25, 'mouseov': 26, 'spec': 27, 'action': 28, 'explicitli': 29, 'fill': 30, 'icon': 31, 'set': 32, 'address': 33, 'awesom': 34, 'bar': 35, 'composit': 36, 'coupl': 37, 'matchbucket': 38, 'pref': 39, 'state': 40, 'unifi': 41, 'user': 42, 'vs': 43, 'browser': 44, 'compon': 45, 'js': 46, 'move': 47, 'unifiedcomplet': 48, 'urlbar': 49, 'highlight': 50, 'implement': 51, 'select': 52, 'around': 53, 'asymmetr': 54, 'box': 55, 'divid': 56, 'ident': 57, 'separ': 58, 'clear': 59, 'extens': 60, 'least': 61, 'let': 62, 'nudg': 63, 'valu': 64, 'fade': 65, 'gradient': 66, 'text': 67, 'tip': 68, 'creat': 69, 'custom': 70, 'experi': 71, 'make': 72, 'plu': 73, 'propos': 74, 'prototyp': 75, 'r

In [103]:
pd.unique(dictionary)

array([   0,    1,    2, ..., 5769, 5770, 5771])

In [57]:
gensim.corpora.dictionary.Dictionary.save('firsttry.dict')

In [126]:
df = pd.DataFrame(list(dictionary.items()),columns = ['Ids','Words'])

df

Ids       Words
0        0       close
1        1         one
2        2        page
3        3      scroll
4        4       space
...    ...         ...
5767  5767    wishlist
5768  5768     legitim
5769  5769  multimedia
5770  5770       dozen
5771  5771     bittorr

[5772 rows x 2 columns]

# Bag of words

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1000)
X = cv.fit_transform(corpus).toarray()
Y = bugs_df.iloc[:, -1].values
# Y = bugs_df['Severity']

In [25]:
len(X[0])

1000

In [26]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [27]:
Y

array(['S4', 'S4', 'S4', ..., 'S6', 'S4', 'S4'], dtype=object)

In [28]:
#Remove outliers/ remove rows having Nan

bugs_df.describe()

index        Bug ID
count  9692.000000  9.692000e+03
mean   4994.404664  1.242127e+06
std    2853.000340  4.602854e+05
min       0.000000  1.095400e+04
25%    2545.750000  1.065393e+06
50%    5029.500000  1.413220e+06
75%    7457.250000  1.573324e+06
max    9911.000000  1.761378e+06

In [29]:
len(bugs_df)

9692

# Split train test

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.20, random_state = 0)

In [31]:
##random shufflin data before train test split
##Try with Multinomial Naive Bayes classifier aswell

# Training the Naive Bayes Model

In [32]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

### Predicting the TestSet Result

In [33]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['S4' 'S4']
 ['S5' 'S3']
 ['S3' 'S4']
 ...
 ['S5' 'S4']
 ['S4' 'S4']
 ['S5' 'S2']]


### Confusion Matrix

In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  3   2   2   0   1   0]
 [  8  27   8   9  11   2]
 [  6  26  39  33  28   6]
 [ 25 233 280 865 212  34]
 [  2   5  18  10  23   0]
 [  2   1   6   6   5   1]]


0.49406910778751933

## MultinomialNB

In [35]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

MultinomialNB()

In [36]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['S4' 'S4']
 ['S4' 'S3']
 ['S4' 'S4']
 ...
 ['S4' 'S4']
 ['S4' 'S4']
 ['S4' 'S2']]


In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[   0    2    3    3    0    0]
 [   0   26   18   20    1    0]
 [   1    7   59   58   13    0]
 [   9   29  289 1181  131   10]
 [   0    2   19   24   13    0]
 [   0    3    6    9    3    0]]


0.6596183599793708

# Logistic Regression

In [38]:
from sklearn.linear_model import LogisticRegression
lr_model = LogisticRegression()
lr_model.fit(X_train,y_train)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [39]:
y_pred = lr_model.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['S4' 'S4']
 ['S4' 'S3']
 ['S4' 'S4']
 ...
 ['S4' 'S4']
 ['S4' 'S4']
 ['S4' 'S2']]


In [40]:
cm_lr = confusion_matrix(y_test, y_pred)
print(cm_lr)
accuracy_score(y_test, y_pred)

[[   0    2    0    6    0    0]
 [   0   18    1   46    0    0]
 [   0    2    5  130    1    0]
 [   0    9   16 1616    8    0]
 [   0    0    0   58    0    0]
 [   0    1    1   19    0    0]]


0.8452810727178959

# SVM

In [41]:
from sklearn.svm import SVC
# svm_model = SVC(kernel='linear',probability=True)
svm_model = SVC(C =100, kernel='linear', gamma='auto')
svm_model.fit(X_train,y_train)

SVC(C=100, gamma='auto', kernel='linear')

In [42]:
y_pred = svm_model.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['S4' 'S4']
 ['S5' 'S3']
 ['S4' 'S4']
 ...
 ['S4' 'S4']
 ['S4' 'S4']
 ['S5' 'S2']]


In [43]:
svm_model = confusion_matrix(y_test, y_pred)
print(svm_model)
accuracy_score(y_test, y_pred)

[[   0    2    0    6    0    0]
 [   5   22    3   32    2    1]
 [   4   21   14   94    4    1]
 [  14   76   89 1422   36   12]
 [   3    2    4   45    4    0]
 [   0    1    5   12    1    2]]


0.7550283651366684

In [ ]:
#Dummy Classification

In [ ]:
#Hypernyms
#Synonyms
#wordnet
#word embedding
#Search existing dic for bug severity
#sentimental finance-- read
#0.1 to 1000 for SVM C para
