In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import opendatasets as od

In [3]:
bugs_df= pd.read_csv("Firefoxbuglist.csv")
# eclispsebugs= pd.read_csv("Eclipsebuglist.csv")
# calendarbugs= pd.read_csv("Calendarbuglist.csv")

In [4]:
# bugs_df = pd.concat([firefoxbugs, eclispsebugs,calendarbugs])

In [5]:
# print(len(firefoxbugs), len(eclispsebugs), len(calendarbugs))

len(bugs_df)

10000

In [6]:
file_name = 'BugCombinedData.xlsx'
  
# saving the excel
#bugs_df.to_excel(file_name)
print('DataFrame is written to Excel File successfully.')

DataFrame is written to Excel File successfully.


In [7]:
bugs_df.head(5)

Bug ID  Product            Component     Assignee    Status Resolution  \
0   276934  Firefox  Keyboard Navigation     aaronlev  RESOLVED  DUPLICATE   
1  1589425  Firefox     Messaging System      abenson  RESOLVED    WONTFIX   
2  1712221  Firefox         New Tab Page  achurchwell  RESOLVED    WONTFIX   
3  1720578  Firefox            Top Sites  achurchwell  RESOLVED  DUPLICATE   
4  1750788  Firefox         New Tab Page  achurchwell  RESOLVED    INVALID   

                                             Summary Change Request Priority  \
0  After closing tab, Space doesn't scroll down o...            ---       P1   
1             Promoting Picture in Picture using CFR            ---       P1   
2            Update "personalize" drawer drop shadow            ---       P1   
3  Sponsored Topsites should retrieve their icons...            ---       P1   
4        Add ability for New Tab Page to set a theme            ---       P1   

  Severity  
0   normal  
1   normal  
2       --  
3       --  
4       --

In [8]:
bugs_df.describe()

Bug ID
count  1.000000e+04
mean   1.255332e+06
std    4.596195e+05
min    1.095400e+04
25%    1.096952e+06
50%    1.425026e+06
75%    1.585128e+06
max    1.761378e+06

In [9]:
bugs_df.describe(include='O')

Product Component Assignee    Status  Resolution  \
count     10000     10000    10000     10000       10000   
unique        1        50      327         1           8   
top     Firefox   General   nobody  RESOLVED  INCOMPLETE   
freq      10000      1367     8045     10000        2999   

                                                  Summary Change Request  \
count                                               10000          10000   
unique                                               9803              1   
top     Intermittent browser/base/content/test/general...            ---   
freq                                                    5          10000   

       Priority Severity  
count     10000     9912  
unique        6       11  
top          P5   normal  
freq       3925     7404

In [10]:
bugs_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Bug ID          10000 non-null  int64 
 1   Product         10000 non-null  object
 2   Component       10000 non-null  object
 3   Assignee        10000 non-null  object
 4   Status          10000 non-null  object
 5   Resolution      10000 non-null  object
 6   Summary         10000 non-null  object
 7   Change Request  10000 non-null  object
 8   Priority        10000 non-null  object
 9   Severity        9912 non-null   object
dtypes: int64(1), object(9)
memory usage: 781.4+ KB


In [11]:
bugs_df=bugs_df.dropna().reset_index(drop=True)

In [12]:
len(bugs_df)

9912

In [13]:
bugs_df = bugs_df[bugs_df["Severity"].str.contains("--")==False].reset_index()

In [14]:
len(bugs_df)

9692

In [15]:
bugs_df.head(5)

index   Bug ID  Product            Component  Assignee    Status  \
0      0   276934  Firefox  Keyboard Navigation  aaronlev  RESOLVED   
1      1  1589425  Firefox     Messaging System   abenson  RESOLVED   
2      5  1060367  Firefox               Search       adw  RESOLVED   
3      6  1326826  Firefox               Search       adw  RESOLVED   
4      7  1328104  Firefox               Search       adw  RESOLVED   

   Resolution                                            Summary  \
0   DUPLICATE  After closing tab, Space doesn't scroll down o...   
1     WONTFIX             Promoting Picture in Picture using CFR   
2  WORKSFORME  [e10s] Search engine add-ons using POST do not...   
3   DUPLICATE  Popup with search suggestions hides on 'moused...   
4   DUPLICATE             Add Search Engine Button Does Not Work   

  Change Request Priority Severity  
0            ---       P1   normal  
1            ---       P1   normal  
2            ---       P1   normal  
3            ---       P1   normal  
4            ---       P1   normal

In [16]:
bugs_df.isnull().sum()

index             0
Bug ID            0
Product           0
Component         0
Assignee          0
Status            0
Resolution        0
Summary           0
Change Request    0
Priority          0
Severity          0
dtype: int64

In [17]:
bugs_df['Severity'].value_counts()

normal      7404
S4           937
major        335
critical     323
minor        258
S3           256
trivial       73
blocker       49
S2            46
S1            11
Name: Severity, dtype: int64

In [18]:
bugs_df.loc[bugs_df["Severity"] == "blocker", "Severity"] = 'S1'
bugs_df.loc[bugs_df["Severity"] == "critical", "Severity"] = 'S2'
bugs_df.loc[bugs_df["Severity"] == "major", "Severity"] = 'S3'
bugs_df.loc[bugs_df["Severity"] == "normal", "Severity"] = 'S4'
bugs_df.loc[bugs_df["Severity"] == "minor", "Severity"] = 'S5'
bugs_df.loc[bugs_df["Severity"] == "trivial", "Severity"] = 'S6'

In [19]:
bugs_df.head(3)

index   Bug ID  Product            Component  Assignee    Status  \
0      0   276934  Firefox  Keyboard Navigation  aaronlev  RESOLVED   
1      1  1589425  Firefox     Messaging System   abenson  RESOLVED   
2      5  1060367  Firefox               Search       adw  RESOLVED   

   Resolution                                            Summary  \
0   DUPLICATE  After closing tab, Space doesn't scroll down o...   
1     WONTFIX             Promoting Picture in Picture using CFR   
2  WORKSFORME  [e10s] Search engine add-ons using POST do not...   

  Change Request Priority Severity  
0            ---       P1       S4  
1            ---       P1       S4  
2            ---       P1       S4

In [20]:
len(bugs_df)

9692

# Correlation Attributes

In [21]:
bugs_df.corr()

#nominal attributes with class label
#Correlation Attributes
#Dictionary-- check in litreture
#dictionary for bug severity 
#Unique Words
#LR SVM

index    Bug ID
index   1.000000  0.061858
Bug ID  0.061858  1.000000

# Cleaning bug summary column

In [22]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to /Users/abyte/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [23]:
corpus = []
for i in range(0,9692):
    review = re.sub('[^a-zA-Z]', ' ', str(bugs_df['Summary'][i]))
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    all_stopwords = stopwords.words('english')
    all_stopwords.remove('not')
    review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
    review = ' '.join(review)
    corpus.append(review)

In [24]:
print(corpus)

['close tab space scroll one page', 'promot pictur pictur use cfr', 'e search engin add on use post not work e', 'popup search suggest hide mousedown button', 'add search engin button not work', 'one hover mouseov color darker match spec', 'icon page action popup explicitli set fill color', 'coupl awesom bar composit matchbucket pref user address bar state unifi vs bar', 'move unifiedcomplet js browser compon urlbar', 'implement select highlight', 'space around ident box separ divid asymmetr', 'nudg let extens set urlbar valu least clear', 'use fade gradient tip text', 'make propos v let experi extens creat result type custom view plu prototyp', 'forc muxer ignor built tip extens tip present', 'nvda screen reader read intervent card get help button mouseov', 'add analyt click send tab notif ui', 'creat dashboard valid data redash', 'crash content process due assert antitrackingcommon cpp', 'content block dispatch state cooki block tracker respons come cach', 'user unabl login pinterest

# Bag of words

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1000)
X = cv.fit_transform(corpus).toarray()
Y = bugs_df.iloc[:, -1].values
# Y = bugs_df['Severity']

In [27]:
len(X[0])

1000

In [28]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [29]:
Y

array(['S4', 'S4', 'S4', ..., 'S6', 'S4', 'S4'], dtype=object)

In [30]:
#Remove outliers/ remove rows having Nan

bugs_df.describe()

index        Bug ID
count  9692.000000  9.692000e+03
mean   4994.404664  1.242127e+06
std    2853.000340  4.602854e+05
min       0.000000  1.095400e+04
25%    2545.750000  1.065393e+06
50%    5029.500000  1.413220e+06
75%    7457.250000  1.573324e+06
max    9911.000000  1.761378e+06

In [31]:
len(bugs_df)

9692

# Split train test

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.20, random_state = 0)

In [33]:
##random shufflin data before train test split
# Encoder = LabelEncoder()
# Train_Y = Encoder.fit_transform(y_train)
# Test_Y = Encoder.fit_transform(y_test)

# Training the Naive Bayes Model

In [34]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

### Predicting the TestSet Result

In [35]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['S4' 'S4']
 ['S5' 'S3']
 ['S3' 'S4']
 ...
 ['S5' 'S4']
 ['S4' 'S4']
 ['S5' 'S2']]


### Confusion Matrix

In [36]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  3   2   2   0   1   0]
 [  8  27   8   9  11   2]
 [  6  26  39  33  28   6]
 [ 25 233 280 865 212  34]
 [  2   5  18  10  23   0]
 [  2   1   6   6   5   1]]


0.49406910778751933

### MultinomialNB

In [37]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

MultinomialNB()

In [38]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['S4' 'S4']
 ['S4' 'S3']
 ['S4' 'S4']
 ...
 ['S4' 'S4']
 ['S4' 'S4']
 ['S4' 'S2']]


In [39]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[   0    2    3    3    0    0]
 [   0   26   18   20    1    0]
 [   1    7   59   58   13    0]
 [   9   29  289 1181  131   10]
 [   0    2   19   24   13    0]
 [   0    3    6    9    3    0]]


0.6596183599793708

# Logistic Regression

In [40]:
from sklearn.linear_model import LogisticRegression
lr_model = LogisticRegression()
lr_model.fit(X_train,y_train)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [41]:
y_pred = lr_model.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['S4' 'S4']
 ['S4' 'S3']
 ['S4' 'S4']
 ...
 ['S4' 'S4']
 ['S4' 'S4']
 ['S4' 'S2']]


In [42]:
cm_lr = confusion_matrix(y_test, y_pred)
print(cm_lr)
accuracy_score(y_test, y_pred)

[[   0    2    0    6    0    0]
 [   0   18    1   46    0    0]
 [   0    2    5  130    1    0]
 [   0    9   16 1616    8    0]
 [   0    0    0   58    0    0]
 [   0    1    1   19    0    0]]


0.8452810727178959

# SVM

In [48]:
from sklearn.svm import SVC
# svm_model = SVC(kernel='linear',probability=True)
svm_model = SVC(C =200, kernel='linear', gamma='auto')
svm_model.fit(X_train,y_train)

SVC(C=200, gamma='auto', kernel='linear')

In [49]:
y_pred = svm_model.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['S4' 'S4']
 ['S5' 'S3']
 ['S4' 'S4']
 ...
 ['S4' 'S4']
 ['S4' 'S4']
 ['S5' 'S2']]


In [50]:
svm_model = confusion_matrix(y_test, y_pred)
print(svm_model)
accuracy_score(y_test, y_pred)

[[   0    3    1    4    0    0]
 [   5   21    5   31    2    1]
 [   4   22   17   91    3    1]
 [  14   84   90 1409   40   12]
 [   3    2    5   43    5    0]
 [   0    2    4   13    1    1]]


0.7493553378029912

In [ ]:
#Dummy Classification

In [ ]:
#Hypername
#Synonyms
#wordnet
#word embedding
#Search existing dic for bug severity
#sentimental finance-- read
#0.1 to 1000 for SVM C para
